SPORT_EVENT_TYPE_MAP = {
    "soccer": "1",
    "football": "1",
    "tennis": "2",
    "golf": "3",
    "cricket": "4",
    "rugby": "5",
    "boxing": "6",
    "horse racing": "7",
    "motorsport": "8",
    "baseball": "11",
    "american football": "6423",
    "basketball": "7522",
    "ice hockey": "7524",
}